name: Harlan Haskins
description: Software Developer
meta_description: "iOS Developer in Rochester, New York"
baseurl: ''

markdown: redcarpet
pygments: true
logo: 'https://0.gravatar.com/avatar/9d670e1bacb9419d68fbb5245e4ecef5?s=300'
paginate: 3

author:
  name: 'Harlan Haskins'
  website: 'http://harlanhaskins.com'
  bio: 'Harlan is a software developer in Rochester, New York.'
  image: 'https://0.gravatar.com/avatar/9d670e1bacb9419d68fbb5245e4ecef5?s=300'

# Details for the RSS feed generator
url:            'http://www.harlanhaskins.com'

# Exlcusion
exclude: [fabfile.py, fabfile.pyc, _site.zip]
