name: Harlan Haskins
description: Software Developer
meta_description: "18 year old iOS Developer in Rochester, New York"
baseurl: '/'

markdown: redcarpet
pygments: true
logo: '/images/vapor_logo.png'
paginate: 3

author:
  name: 'Harlan Haskins'
  website: 'http://harlanhaskins.com'
  bio: 'Your Bio'
  image: '/images/profile.png'

# Details for the RSS feed generator
url:            'blog url'
