name: Harlan Haskins
description: Software Developer
meta_description: 'Software Developer in Cupertino, California'
baseurl: ''

markdown: redcarpet

redcarpet:
  extensions: ["strikethrough", "tables"]

highlighter: pygments
logo: 'https://0.gravatar.com/avatar/9d670e1bacb9419d68fbb5245e4ecef5?s=300'
paginate: 3

author:
  name: 'Harlan Haskins'
  website: 'http://harlanhaskins.com'
  bio: 'Harlan is a software developer in Sunnyvale, California.'
  image: 'https://0.gravatar.com/avatar/9d670e1bacb9419d68fbb5245e4ecef5?s=300'

# Details for the RSS feed generator
url: 'http://harlanhaskins.com'

# Exlcusion
exclude: [fabfile.py, fabfile.pyc, _site.zip]
